# Generated by Django 5.2.3 on 2025-06-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='repeat_interval',
            field=models.CharField(blank=True, choices=[('daily', '毎日'), ('weekly', '毎週')], max_length=10, null=True),
        ),
    ]
