# Generated by Django 5.2.3 on 2025-06-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_taskmodel_repeat_taskmodel_repeat_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
